language: go
go:
  - 1.18.x

install: 
  - go install github.com/gohugoio/hugo@latest

script: 
  - mkdir -p themes/beautifulhugo && git clone https://github.com/halogenica/beautifulhugo.git themes/beautifulhugo
  - hugo --theme beatuifulhugo

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: public
  on:
    branch: main